# Generated by Django 3.1.5 on 2021-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(blank=True, to='app1.User'),
        ),
    ]
