# Generated by Django 3.1.2 on 2021-01-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_auto_20210107_2055'),
        ('polls', '0002_auto_20210107_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='vote_usr', to='app1.User'),
        ),
    ]
