# Generated by Django 3.0.6 on 2020-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notofication_topic', models.CharField(max_length=50)),
                ('notofication_content', models.CharField(max_length=1000)),
                ('notofication_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
