# Generated by Django 3.0.6 on 2020-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_DOB', models.DateField()),
                ('user_password', models.CharField(max_length=100)),
                ('user_Codechef_id', models.CharField(max_length=50, null=True)),
                ('user_Codeforces_id', models.CharField(max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
