# Generated by Django 3.0.6 on 2020-06-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200617_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seen_notification',
            name='id',
        ),
        migrations.AlterField(
            model_name='seen_notification',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.User'),
        ),
    ]
