# Generated by Django 3.0.6 on 2020-06-22 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200618_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_start_date', models.DateTimeField(auto_now_add=True)),
                ('event_end_date', models.DateTimeField(auto_now_add=True)),
                ('event_details', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photo', models.ImageField(upload_to='events_images/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Event')),
            ],
        ),
    ]
