# Generated by Django 3.0.6 on 2020-06-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200624_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_photos',
            name='event_photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
