# Generated by Django 3.0.6 on 2020-06-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200624_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_photos',
            name='event_photo',
            field=models.ImageField(null=True, upload_to='static/media/uploded/event_photos'),
        ),
    ]
