# Generated by Django 3.0.6 on 2020-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20200624_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile_photo',
            field=models.ImageField(default='static/media/user.png', upload_to='profile/'),
        ),
    ]
