# Generated by Django 3.0.6 on 2020-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_user_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_photo',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
