# Generated by Django 3.0.6 on 2020-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20200624_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_post',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
