# Generated by Django 3.0.6 on 2020-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20200625_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_registation',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
