# Generated by Django 3.0.6 on 2020-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_event_event_registation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_files',
            name='resource',
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lable',
        ),
        migrations.DeleteModel(
            name='Resource_Files',
        ),
    ]
