# Generated by Django 3.0.6 on 2020-06-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20200630_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
