# Generated by Django 3.0.6 on 2020-06-30 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20200630_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 45, 30, 956116)),
        ),
    ]
