# Generated by Django 3.0.6 on 2020-06-30 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20200630_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 55, 56, 777494)),
        ),
    ]
