# Generated by Django 3.0.6 on 2020-06-30 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20200630_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 8, 8, 885694)),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_link',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
