# Generated by Django 3.0.6 on 2020-09-02 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20200902_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 11, 41, 2, 291348)),
        ),
    ]
