# Generated by Django 3.0.6 on 2020-09-02 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20200902_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_Codechef_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_Codeforces_id',
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 11, 55, 15, 114858)),
        ),
    ]
