# Generated by Django 3.1.1 on 2020-09-02 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20200902_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 15, 41, 31, 737506)),
        ),
    ]
