# Generated by Django 3.1.1 on 2020-09-03 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20200902_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_github',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='user',
            name='user_linkedin',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 4, 45, 193137)),
        ),
    ]
