# Generated by Django 3.1.2 on 2020-10-22 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20200903_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 14, 18, 23, 983529)),
        ),
    ]
