# Generated by Django 2.2.7 on 2020-10-23 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20201023_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 21, 30, 16, 546546)),
        ),
    ]
