# Generated by Django 2.2.7 on 2020-10-23 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_auto_20201023_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insta',
            name='link',
        ),
        migrations.AddField(
            model_name='insta',
            name='insta_link',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 21, 35, 58, 685948)),
        ),
    ]
