# Generated by Django 2.2.7 on 2020-10-23 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_auto_20201023_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 22, 36, 33, 628810)),
        ),
    ]
