# Generated by Django 2.2.7 on 2020-10-26 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_auto_20201026_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 22, 11, 11, 673779)),
        ),
    ]
