# Generated by Django 2.2.7 on 2020-10-27 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_auto_20201026_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 15, 54, 20, 789912)),
        ),
    ]
