# Generated by Django 2.2.7 on 2020-11-02 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_auto_20201030_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 11, 54, 5, 833)),
        ),
    ]
