# Generated by Django 2.2.7 on 2020-11-11 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_auto_20201102_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_reg',
            field=models.ManyToManyField(null=True, related_name='events_id', to='app1.Event'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 23, 4, 31, 941705)),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attending', serialize=False, to='app1.User')),
                ('is_attending', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='app1.Event')),
            ],
        ),
    ]
