# Generated by Django 2.2.7 on 2020-11-11 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_auto_20201111_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 23, 17, 34, 631201)),
        ),
    ]
