# Generated by Django 2.2.7 on 2020-11-11 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_auto_20201111_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events_reg',
            field=models.ManyToManyField(null=True, related_name='events_id', to='app1.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 23, 18, 22, 850308)),
        ),
    ]
