# Generated by Django 2.2.7 on 2020-12-22 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_auto_20201222_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 21, 44, 8, 669234)),
        ),
    ]
