# Generated by Django 2.2.7 on 2020-12-23 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_auto_20201223_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 15, 33, 4, 628972)),
        ),
    ]
