# Generated by Django 2.2.7 on 2020-12-24 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_auto_20201223_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 17, 53, 25, 633563)),
        ),
    ]
