# Generated by Django 2.2.7 on 2020-12-25 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_auto_20201224_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to='event_photos/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 13, 49, 2, 238531)),
        ),
    ]
