# Generated by Django 2.2.7 on 2020-12-26 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_auto_20201225_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(null=True, related_name='red_usr', to='app1.User'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 12, 42, 22, 290596)),
        ),
    ]
