# Generated by Django 2.2.7 on 2020-12-26 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_auto_20201226_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='non_vitians',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 13, 2, 49, 474675)),
        ),
    ]
