# Generated by Django 2.2.7 on 2020-12-28 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_auto_20201226_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_reg_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 15, 15, 25, 911209)),
        ),
    ]
