# Generated by Django 3.1.4 on 2020-12-28 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_auto_20201228_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 18, 58, 13, 753595)),
        ),
        migrations.AlterField(
            model_name='user',
            name='events_reg',
            field=models.ManyToManyField(blank=True, related_name='events_id', to='app1.Event'),
        ),
    ]
