# Generated by Django 3.1.2 on 2020-12-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_auto_20201228_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 18, 59, 30, 101431)),
        ),
    ]
