# Generated by Django 3.1.2 on 2020-12-30 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_auto_20201228_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ffcs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 18, 18, 39, 232544)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_photo',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
