# Generated by Django 3.1.2 on 2021-01-02 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_auto_20201230_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 13, 5, 36, 152450)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_github',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_insta',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_linkedin',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
