# Generated by Django 3.1.2 on 2021-01-04 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_auto_20210102_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_portfolio',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 8, 27, 588559)),
        ),
    ]
