# Generated by Django 3.1.2 on 2021-01-07 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_auto_20210104_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 20, 55, 25, 833413)),
        ),
    ]
