# Generated by Django 3.1.2 on 2021-01-09 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_auto_20210107_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_vitians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('college', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='red_usr', to='app1.User'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 17, 9, 19, 165844)),
        ),
    ]
