# Generated by Django 3.1.2 on 2021-01-18 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0078_auto_20210109_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_Codechef_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_Codeforces_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 12, 47, 11, 42758)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_github',
            field=models.CharField(blank=True, default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_insta',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_linkedin',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
