# Generated by Django 3.1.2 on 2021-01-18 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0080_auto_20210118_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_Codeforces_id',
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 13, 56, 54, 87391)),
        ),
    ]
