# Generated by Django 3.1.2 on 2021-02-13 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0082_auto_20210130_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 15, 36, 7, 185037)),
        ),
    ]
