# Generated by Django 3.1.2 on 2021-02-13 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_auto_20210213_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 15, 38, 7, 151897)),
        ),
    ]
