# Generated by Django 3.1.2 on 2021-02-23 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_auto_20210221_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 11, 43, 23, 737807)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Codechef_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Codeforces_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
