# Generated by Django 3.1.2 on 2021-04-25 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_auto_20210223_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tech', models.BooleanField(default=False)),
                ('cont', models.BooleanField(default=False)),
                ('design', models.BooleanField(default=False)),
                ('event', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 23, 44, 59, 225416)),
        ),
    ]
