# Generated by Django 3.1.2 on 2021-04-25 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0087_auto_20210425_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 23, 48, 32, 60386)),
        ),
    ]
