# Generated by Django 3.1.2 on 2021-04-25 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_auto_20210425_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='cont',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='design',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='tech',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 1, 15, 27, 835377)),
        ),
    ]
