# Generated by Django 3.1.2 on 2021-05-16 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0091_auto_20210516_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ManyToManyField(blank=True, to='app1.User'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 22, 3, 37, 458091)),
        ),
    ]
