# Generated by Django 3.1.2 on 2021-06-10 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0094_auto_20210516_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 20, 2, 37, 917358)),
        ),
    ]
